[project]
name = "maestro"
version = "0.0.2"
description = "A simple Python task orchestrator"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.3",
    "pyyaml>=6.0",
    "networkx>=3.1",
    "rich",
]

[project.scripts]
maestro = "maestro.cli:app"

[project.optional-dependencies]
test = [
    "pytest",
    "mypy"
]
