name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v1.0.1, etc.
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install .
        uv pip install .[test]

    - name: Run tests
      run: pytest

  release:
    needs: test # This job depends on the 'test' job passing
    if: startsWith(github.ref, 'refs/tags/v') # Only run if the push is a tag starting with 'v'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |-
          Automated release for tag ${{ github.ref_name }}.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}